# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    strategy:
      matrix:
        node-version: [18, 20, 22, 24, latest]
    steps:
      - uses: actions/checkout@v6
      - uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: |
            ${{ secrets.RSA_KEY }}
            ${{ secrets.ECDSA_256_KEY }}
            ${{ secrets.ECDSA_384_KEY }}
            ${{ secrets.ECDSA_521_KEY }}
            ${{ secrets.ED25519_KEY }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint
      - run: npm run coverage
      - run: node ./dist/src/cli.js --help
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v6
        if: ${{ !cancelled() && matrix.node-version == 'latest' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: coverage
          files: ./coverage/lcov.info
          disable_search: true
      - name: Upload test results to Codecov
        uses: codecov/codecov-action@v6
        if: ${{ !cancelled() && matrix.node-version == 'latest' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          report_type: test_results
          files: ./test-results.xml
          disable_search: true
      - name: Publish test report
        uses: mikepenz/action-junit-report@v6
        if: ${{ (success() || failure()) && matrix.node-version == 'latest'  }}
        with:
          report_paths: ./test-results.xml
